"""Public import surface for Semantic Geometry Builder."""

from semantic_geometry_builder.ir import (
    AtomicVolumeRecord,
    BBox3D,
    Coordinate,
    CutHostOperationRecord,
    DimensionLiteral,
    FinalPhysicalGroupRecord,
    FinalTopologyRecord,
    GeometryBuildInput,
    GmshDimTag,
    InterfaceKindLiteral,
    InterfacePatchRecord,
    LayoutPolygonSpec,
    PolygonRing,
    PrimitiveEntityRecord,
    RingPatchRecord,
    RouteLiteral,
    RouteMaterializationRecord,
    RoutePolicyRecord,
    SemanticEntitySpec,
    SemanticGeometryBuilder,
    SheetImprintOperationRecord,
    SolverUseLiteral,
    Vector3D,
)

__all__ = [
    "AtomicVolumeRecord",
    "BBox3D",
    "Coordinate",
    "CutHostOperationRecord",
    "DimensionLiteral",
    "FinalPhysicalGroupRecord",
    "FinalTopologyRecord",
    "GeometryBuildInput",
    "GmshDimTag",
    "InterfaceKindLiteral",
    "InterfacePatchRecord",
    "LayoutPolygonSpec",
    "PolygonRing",
    "PrimitiveEntityRecord",
    "RingPatchRecord",
    "RouteLiteral",
    "RouteMaterializationRecord",
    "RoutePolicyRecord",
    "SemanticEntitySpec",
    "SemanticGeometryBuilder",
    "SheetImprintOperationRecord",
    "SolverUseLiteral",
    "Vector3D",
]
